// includes: null-components.min.js, null-functions.min.js, null-form-validate.js
/*
 * Null JS v1.0.0 (https://null-js.com)
 * Copyright (c) 2023 Null JS - null-components.min.js
 * Licensed under MIT (https://opensource.org/licenses/MIT)
*/
function null_accordion(parentSelector,showFirst=false){const parent=document.querySelector(parentSelector);if(parent){var buttons,contents,icons;buttons=parent.querySelectorAll('.null-accordion');contents=parent.querySelectorAll('.null-accordion-content-container');icons=parent.querySelectorAll('.null-accordion-icon');buttons.forEach((button,i)=>{button.setAttribute('id',`null-${i}`);button.setAttribute('aria-expanded',false);button.setAttribute('aria-controls',`null-panel-id-${i}`);const number=i+1;const isEven=number%2===0;const numberType=isEven?"even":"odd";button.parentElement.setAttribute("data-null-number",numberType);const content=button.nextElementSibling;content.setAttribute('aria-labelledby',`null-${i}`);content.setAttribute('role','region');content.setAttribute('id',`null-panel-id-${i}`);const icon=button.querySelector('.null-accordion-icon');icon.textContent='+';button.addEventListener('click',()=>{if(parseInt(content.style.height)!==content.scrollHeight){content.style.height=`${content.scrollHeight}px`;icon.textContent='-';}else{content.style.height='0px';icon.textContent='+';}
contents.forEach((c,b)=>{if(b!==i){c.style.height='0px';const otherIcon=buttons[b].querySelector('.null-accordion-icon');otherIcon.textContent='+';}});});});if(showFirst){const firstContent=contents[0];const firstButton=buttons[0];firstContent.style.height='auto';const height=`${firstContent.offsetHeight}px`;firstContent.style.height=height;const icon=firstButton.querySelector('.null-accordion-icon');icon.textContent='-';}}}
function null_alert(){let nullAlertExit=document.querySelectorAll(".null-alert-exit-icon");if(nullAlertExit){for(let i=0;i<nullAlertExit.length;i++){nullAlertExit[i].addEventListener("click",function(){let nullAlertParent=nullAlertExit[i].parentNode.parentNode;nullAlertExit[i].parentNode.parentNode.style.opacity='0';setTimeout(function(){nullAlertParent.remove();},500);})}}}
null_alert();(function(){const dropDownButton=document.querySelectorAll(".null-dropdown-button");for(let i=0;i<dropDownButton.length;i++){dropDownButton[i].addEventListener("click",function(){let container=dropDownButton[i].nextElementSibling
if(container.clientHeight){if(container.classList.contains("show")){container.classList.remove("show");}
container.style.height=0;container.removeAttribute('style');if(dropDownButton[i].classList.contains("active")){dropDownButton[i].classList.remove("active");}}else{wrapper=container.querySelector(".null-dropdown-menu");container.style.height=wrapper.clientHeight+"px";container.style.opacity=1;container.classList.add("show");}
if(dropDownButton[i].querySelector("svg").classList.contains("active")){dropDownButton[i].querySelector("svg").classList.remove("active");}else{dropDownButton[i].querySelector("svg").classList.add("active");}})}
document.addEventListener('click',function(e){let dropdown=document.querySelectorAll(".null-dropdown.show ");dropdown.forEach(function(el){el.parentElement.querySelector(".null-dropdown-button").classList.add("active");if(el!=e.target.nextElementSibling&&!e.target.matches('.null-drop-down-menu')){el.style.height=0;el.removeAttribute('style');if(el.classList.contains("show")){el.classList.remove("show");}
if(el.parentElement.querySelector(".null-dropdown-button").classList.contains("active")){el.parentElement.querySelector(".null-dropdown-button").classList.remove("active");}
if(el.parentElement.querySelector("button svg")){el.parentElement.querySelector("button svg").classList.remove("active");}else{el.parentElement.querySelector("a svg").classList.remove("active");}}});})
function addActive(x){if(!x)return false;removeActive(x);if(currentFocus>=x.length)currentFocus=0;if(currentFocus<0)currentFocus=(x.length-1);x[currentFocus].classList.add("active");}
function removeActive(x){for(var i=0;i<x.length;i++){x[i].classList.remove("active");}}
currentFocus=-1;document.addEventListener("keydown",function(e){const buttonActive=document.querySelectorAll(".null-dropdown-button.active");for(let i=0;i<buttonActive.length;i++){e.preventDefault();if(e.keyCode==40){currentFocus++;addActive(buttonActive[i].parentElement.querySelector(".null-dropdown-menu").children);}else if(e.keyCode==38){currentFocus--;addActive(buttonActive[i].parentElement.querySelector(".null-dropdown-menu").children);}else if(e.keyCode==13){e.preventDefault();if(currentFocus>-1){buttonActive[i].parentElement.querySelector(".null-dropdown-menu li.active a").click();}}}});})();function null_list(listID){const nullSearchInput=document.querySelector(`${listID}#null-list-search-input`);const nullSearchResults=document.querySelector(`${listID}.null-list-results`);const nullSearchResult=document.querySelectorAll(`${listID}.null-list-result`);const nullResultTitle=nullSearchResults?.querySelectorAll(`${listID}.null-list-result-name`);function null_list_delay(func,ms){let timer=0;return function(...args){clearTimeout(timer);timer=setTimeout(func.bind(this,...args),ms||0);};}
if(nullSearchInput){nullSearchInput.addEventListener("keyup",null_list_delay(()=>{const nullSearchInputFilter=nullSearchInput.value.replace(/\s/g,"").toUpperCase();let nullNoResults=true;nullResultTitle?.forEach((match)=>{const textValue=match.textContent||match.innerHTML;if(textValue.toUpperCase().indexOf(nullSearchInputFilter)>-1){nullNoResults=false;nullSearchResults.appendChild(match.closest(".null-list-result"));}else{const resultToRemove=match.closest(".null-list-result");if(document.contains(resultToRemove)){resultToRemove.remove();}}
document.querySelector(`${listID}.null-list-result-no-records-found`).innerHTML=nullNoResults?"<div>No records found</div>":"";});},500));}
let nullCountRecords=0;const null_list_total_results=document.querySelector(`${listID}#null-list-total-results span`);nullSearchResult.forEach((result,i)=>{nullCountRecords++;result.setAttribute("data-null-id",i+1);if((i+1)%2==0){result.setAttribute("data-null-number","even");}else{result.setAttribute("data-null-number","odd");}});if(nullSearchResults){null_list_total_results.innerHTML=nullSearchResults.querySelectorAll('.null-list-result').length;}}
function null_modal(){const nullOpenModalButton=document.querySelectorAll('[data-null-modal-target]');const nullCloseModalButton=document.querySelectorAll('[data-close-button]');const nullModal=document.querySelectorAll('.null-modal-container');const nullBody=document.body;nullCloseModalButton.forEach(function(button){button.addEventListener('click',()=>{const modal=button.closest(".null-modal-container");nullBody.classList.remove("null-modal-body-overflow-hidden");nullCloseModal(modal);})});nullOpenModalButton.forEach(function(button){button.addEventListener('click',()=>{const modal=document.querySelector(button.dataset.nullModalTarget);nullBody.classList.add("null-modal-body-overflow-hidden");nullOpenModal(modal);})});function nullOpenModal(modal){if(modal==null)return;modal.classList.add('active');}
function nullCloseModal(modal){if(modal==null)return;modal.classList.remove('active');}
window.addEventListener('click',nullOutSideClick);function nullOutSideClick(e){for(let i=0;i<nullModal.length;i++){if(e.target==nullModal[i]){nullModal[i].classList.remove('active');nullBody.classList.remove("null-modal-body-overflow-hidden");}}}}
null_modal();(function(){const mobileIcon=document.querySelector(".null-navbar-menu-icon-contianer");const Menu=document.querySelector(".null-navbar-links");const backDrop=document.querySelector(".null-navbar-back-drop");const body=document.body;const search=document.querySelector(".null-navbar-search svg");const searchForm=document.querySelector(".null-navbar-form");const searchContainer=document.querySelector(".null-navbar-form-container");function null_nav_bar_back_drop(){const newDiv=document.createElement("div");newDiv.classList.add("null-navbar-back-drop");document.body.appendChild(newDiv);}
function null_nav_bar_back_drop_search(){let checkBackDrop=document.querySelector(".null-navbar-back-drop");checkBackDrop.onclick=()=>{checkBackDrop.remove();if(body.classList.contains("null-navbar-body-overflow-hidden")){body.classList.remove("null-navbar-body-overflow-hidden");}
Menu.classList.remove("active");}}
if(mobileIcon){mobileIcon.onclick=()=>{Menu.classList.add("active");body.classList.add("null-navbar-body-overflow-hidden");null_nav_bar_back_drop();null_nav_bar_back_drop_search();}}
function hideBackDrop(x){let elementExist=document.querySelector(".null-navbar-back-drop");let activeNav=document.querySelector(".null-navbar-links");let body=document.body;if(x.matches){if(elementExist){elementExist.removeAttribute('style');body.style.overflow="";if(activeNav){if(activeNav.classList.contains("active")){activeNav.removeAttribute('style');}}}}else{if(elementExist){elementExist.style.display="none";body.style.overflow="auto";}
if(activeNav){if(activeNav.classList.contains("active")){activeNav.style.transition="none";}}}}
let mediaQuery=window.matchMedia("(max-width: 992px)");hideBackDrop(mediaQuery);mediaQuery.addListener(hideBackDrop);window.addEventListener("orientationchange",()=>{if(backDrop){backDrop.remove();}
body.classList.remove("null-navbar-body-overflow-hidden");Menu.classList.remove("active");});if(search){search.onclick=()=>{if(searchForm.classList.contains("active")){searchForm.classList.remove("active");searchContainer.classList.remove("active");}else{searchForm.classList.add("active");searchContainer.classList.add("active");searchForm.querySelector(".null-navbar-form-input").focus();}}}
window.addEventListener('click',hideSearch);function hideSearch(e){if(e.target!=search&&e.target.parentNode!=searchContainer&&e.target.parentNode!=searchForm){if(searchForm){searchForm.classList.remove("active");}
if(searchContainer){searchContainer.classList.remove("active");}}}})();function null_circular_progress(id,args){const nullCircularProgress=document.querySelector(`#${id}.null-circular-progress`);const nullCircularProgressValue=document.querySelector(`#${id}.null-circular-progress-value`);let defaults={endValue:100,speed:50};let params={...defaults,...args};let progressStartValue=0,progressEndValue=params.endValue,speed=params.speed;if(nullCircularProgress){let nullProgress=setInterval(()=>{progressStartValue++;nullCircularProgressValue.textContent=`${progressStartValue}%`;nullCircularProgressValue.setAttribute("data-null-circular-progress-value",progressStartValue+'%');nullCircularProgressValue.setAttribute("data-null-circular-progress-degree",(progressStartValue*3.6)+"deg");nullCircularProgress.style.background=`conic-gradient(var(--null-color-main)${progressStartValue*3.6}deg,#f6f7f9 0deg)`;if(progressStartValue==progressEndValue){clearInterval(nullProgress)}},speed);}}
null_circular_progress("s1",{endValue:30,speed:50});function null_tabs(){const nullTabs=document.querySelectorAll('[data-tab-target]');const nullTabContents=document.querySelectorAll('[data-tab-content]');let nullPrevTab=document.querySelector('[data-tab-target].active');const nullHash=window.location.hash;const nullActiveTab=nullHash?document.querySelector(`[data-tab-target="${nullHash}"]`):null;const nullDefaultTab=nullTabs[0];if(!nullTabs.length){return;}
const nullInitialTab=nullActiveTab||nullDefaultTab;if(!nullInitialTab){console.error(`No valid tab found for hash"${nullHash}"`);return;}
nullInitialTab.classList.add('active');const nullInitialContent=document.querySelector(nullInitialTab.dataset.tabTarget);if(!nullInitialContent){console.error(`No content found for tab"${nullInitialTab.dataset.tabTarget}"`);return;}
nullInitialContent.classList.add('active');nullTabs.forEach(nullTab=>{nullTab.addEventListener('click',(event)=>{event.preventDefault();if(nullPrevTab){nullPrevTab.classList.remove('active');}
const nullTarget=document.querySelector(nullTab.dataset.tabTarget);nullTabContents.forEach(nullTabContent=>{nullTabContent.classList.remove('active');})
nullTabs.forEach(nullTab=>{nullTab.classList.remove('active');})
nullTab.classList.add('active');nullTarget.classList.add('active');history.replaceState(null,null,`#${nullTarget.id}`);nullPrevTab=nullTab;})})
window.addEventListener('hashchange',()=>{const nullHash=window.location.hash;const nullNewActiveTab=nullHash?document.querySelector(`[data-tab-target="${nullHash}"]`):null;const nullNewDefaultTab=nullTabs[0];const nullTabToActivate=nullNewActiveTab||nullNewDefaultTab;if(!nullTabToActivate){console.error(`No valid tab found for hash"${nullHash}"`);return;}
if(nullPrevTab){nullPrevTab.classList.remove('active');}
nullTabToActivate.click();nullPrevTab=nullTabToActivate;});}
null_tabs();function null_toast(){const nullToastButton=document.querySelectorAll(".null-toast-button");const nullToastCloseButton=document.querySelectorAll(".null-toast-close-container");let nullTimerOne;let nullTimerTwo;for(let i=0;i<nullToastButton.length;i++){nullToastButton[i].addEventListener("click",()=>{let nullToastContainer=nullToastButton[i].parentElement;let nullToast=nullToastContainer.querySelector(".null-toast");let nullToastProgress=nullToastContainer.querySelector(".null-toast-progress");nullToastButton[i].disabled=true;nullToastButton[i].classList.add('null-button-disabled');nullToast.classList.add("active");nullToastProgress.classList.add("active");nullTimerOne=setTimeout(()=>{nullToast.classList.remove("active");nullToastButton[i].disabled=false;nullToastButton[i].classList.remove('null-button-disabled');},5000);nullTimerTwo=setTimeout(()=>{nullToastProgress.classList.remove("active");},5300);});}
for(let i=0;i<nullToastCloseButton.length;i++){nullToastCloseButton[i].addEventListener("click",()=>{let nullToast=nullToastCloseButton[i].parentElement;let nullToastProgress=nullToast.querySelector(".null-toast-progress");nullToast.classList.remove("active");nullToastButton[i].disabled=false;nullToastButton[i].classList.remove('null-button-disabled');setTimeout(()=>{nullToastProgress.classList.remove("active");},300);clearTimeout(nullTimerOne);clearTimeout(nullTimerTwo);});}}
null_toast();function null_tree(element,showFirst=false){if(element){element=document.querySelectorAll(element);for(const el of element){if(showFirst){el.querySelector(".null-tree-list ul").classList.add("active");}}}else{const nullTreeLists=document.querySelectorAll(".null-tree-list");for(const nullTreeList of nullTreeLists){nullTreeList.querySelector("div").addEventListener("click",function(){nullTreeList.querySelector("ul").classList.toggle("active");});}}}
null_tree();function null_scroll_to_top(scrollY=300){const nullToTop=document.querySelector(".null-scroll-to-top-container");if(nullToTop==null)return;window.addEventListener("scroll",function(){const nullScrollTop=window.pageYOffset||document.documentElement.scrollTop;const nullWindowHeight=document.documentElement.scrollHeight-document.documentElement.clientHeight;const nullScrollPercent=nullScrollTop / nullWindowHeight*100;nullToTop.style.background=`conic-gradient(var(--null-color-main)${nullScrollPercent}%,var(--null-color-light-grey)${nullScrollPercent}%)`;if(nullScrollTop>=scrollY){nullToTop.classList.add("active");nullToTop.onclick=function(){window.scrollTo({top:0,left:0,behavior:"smooth"});};}else{if(nullToTop.classList.contains("active")){nullToTop.classList.remove("active");}}});}
null_scroll_to_top();

/*
 * Null JS v1.0.0 (https://null-js.com)
 * Copyright (c) 2023 Null JS -  null-functions.min.js
 * Licensed under MIT (https://opensource.org/licenses/MIT)
*/
function null_translator(el,arg){element=document.querySelectorAll(el);for(let i=0;i<element.length;i++){for(const prop in arg){if(document.documentElement.lang.toLowerCase()===prop){element[i].innerText=arg[prop];}}}}
const null_add_style=((nullStyle)=>{const sheet=document.head.appendChild(nullStyle).sheet;return(selectors,styles)=>{if(!selectors||!styles){throw new Error('Invalid parameters for null_add_style');}
if(typeof selectors==='string'){selectors=[selectors];}
selectors.forEach((selector)=>{const propText=typeof styles==="string"?styles:Object.keys(styles).map((prop)=>{return`${prop}:${(prop==="content")?"'"+styles[prop]+"'":styles[prop]}`;}).join(";");sheet.insertRule(`${selector}{${propText}}`,sheet.cssRules.length);});};})(document.createElement("style"));function null_truncate(el,num){const elements=document.querySelectorAll(el);if(typeof el!=="string"||el.charAt(0)!=="."){throw new Error("Please enter a valid class name starting with '.'");}
if(!(typeof num==="number"&&Number.isInteger(num)&&num>0)){throw new Error(`Please enter a valid number.You entered:${num}`);}
for(let i=0;i<elements.length;i++){let text=elements[i].textContent.trim();if(text.length<=num)continue;let lastSpace=text.lastIndexOf(" ",num);let truncated=text.substring(0,lastSpace>=0?lastSpace:num).trim();if(lastSpace<0||lastSpace+1+text.length-truncated.length<=num){elements[i].textContent=truncated;}else{elements[i].textContent=truncated+" ...";}}}
function null_create_element(tag,args){let defaults={text:null,id:null,title:null,html:null,classes:null,attributes:{},append:{},src:null,href:null,callBack:null};let params={...defaults,...args};const element=document.createElement(tag);if(params.text){element.innerText=params.text;}
if(params.id){element.setAttribute("id",params.id);}
if(params.title){element.setAttribute("title",params.title);}
if(params.html){element.innerHTML=params.html;}
if(params.classes){element.classList.add(...params.classes);}
if(params.attributes){for(const property in params.attributes){element.setAttribute(property,params.attributes[property]);}}
if(params.callBack){params.callBack(element);}
if(params.append){const{position,target}=params.append;switch(position){case"inside":target.appendChild(element);break;case"before":target.parentNode.insertBefore(element,target);break;case"after":target.parentNode.insertBefore(element,target.nextSibling);break;default:throw new Error(`Invalid append position:${position}`);}}
return element;}
function null_add_classes(selector,classes){const elements=document.querySelectorAll(selector);for(let i=0;i<elements.length;i++){const elementClasses=elements[i].getAttribute("class");const existingClasses=elementClasses?elementClasses.split(" "):[];const combinedClasses=[...existingClasses,...classes];const uniqueClasses=[...new Set(combinedClasses)];const finalClasses=uniqueClasses.join(" ");elements[i].setAttribute("class",finalClasses);}}
function null_string_to_array(str){if(typeof str!=="string"){throw new TypeError("Input must be a string");}
const trimmedStr=str.trim();if(trimmedStr===""){return[];}
const arr=trimmedStr.split(/\s+/);return arr;}
function null_count_duplicates_in_array_to_object(arr){if(!Array.isArray(arr)){throw new TypeError("Input must be an array");}
const countObject={};arr.forEach((item)=>{countObject[item]=(countObject[item]||0)+1;});return countObject;}
function null_remove_duplicates_from_array(arr){if(!Array.isArray(arr)){throw new TypeError("Input must be an array");}
const uniqueItems=[...new Set(arr)];return uniqueItems;}
function null_remove_value_from_array(arr,value){if(!Array.isArray(arr)){throw new TypeError("Input must be an array");}
if(value===undefined){throw new Error("A value must be provided");}
const newArray=arr.filter((item)=>item!==value);return newArray;}
function null_remove_values_from_array(array,...theArgs){if(!Array.isArray(array)){throw new Error("The first argument must be an array.");}
if(!Array.isArray(theArgs)){throw new Error("The second argument must be an array.");}
return array.filter(val=>!theArgs.includes(val));}
function null_count_most_frequent(arr){if(!Array.isArray(arr)){throw new TypeError('Expected an array');}
if(arr.length===0){return null;}
const mostFrequent=arr.reduce((acc,val)=>{acc[val]=(acc[val]||0)+1;if(acc[val]>acc.mostFreq.freq){acc.mostFreq.value=val;acc.mostFreq.freq=acc[val];}
return acc;},{mostFreq:{value:null,freq:0}}).mostFreq;return mostFrequent;}
function null_delete_keys_from_object(keysArray,obj){if(!Array.isArray(keysArray)){throw new Error("keysArray parameter must be an array");}
if(typeof obj!=="object"||obj===null||Array.isArray(obj)){throw new Error("obj parameter must be an object");}
const newObject={};const keys=Object.keys(obj);for(const key of keys){if(!keysArray.includes(key)){newObject[key]=obj[key];}}
return newObject;}
function null_exclude_keys_from_object(nullObject,exclude=[]){if(typeof nullObject!=="object"||nullObject===null||Array.isArray(nullObject)){throw new Error("The first argument must be an object");}
return Object.keys(nullObject).reduce((target,k)=>{if(exclude.length){if(exclude.indexOf(k)<0)target[k]=nullObject[k];}
return target;},{});}
function null_include_keys_to_object(nullObject,include={}){if(typeof nullObject!=="object"||nullObject===null||Array.isArray(nullObject)){throw new Error("The first argument must be an object");}
return Object.keys(include).reduce((target,k)=>{target[k]=include[k];return target;},{...nullObject});}
function null_extract_values_from_array_to_new_array(array,extractValues){return array.filter(val=>extractValues.includes(val));}
function null_process(el,callBack){if(el.startsWith("#")){const element=document.querySelector(el);if(element){callBack(element);return[element];}else{throw new Error(`Element with ID"${el}"not found.`);}}
else if(el.startsWith(".")){const className=el.substring(1);const elements=Array.from(document.getElementsByClassName(className));elements.forEach(element=>{callBack(element);});return elements;}
else{throw new Error(`Invalid selector"${el}"`);}}

/*
* Null JS v1.0.0 (https://null-js.com)
* Copyright (c) 2023 Null JS - null-form-validate.js
* Licensed under MIT (https://opensource.org/licenses/MIT)
*/
function null_initialize_form_fields(form,args){for(let field in args){let input=form.querySelector("#"+field);if(!input){console.error(`Input not found for field:${field}`);continue;}
if(args[field].placeholder){input.setAttribute("placeholder",args[field].placeholder);}
if(args[field].type){input.setAttribute("type",args[field].type);}}}
function null_password_validation(fieldValue,passwordOptions,customErrorMessages,errorContainer){if(typeof customErrorMessages==="undefined"){customErrorMessages={};}
const letters=/[a-zA-Z]/;const numbers=/[0-9]/;const symbols=/[-!$%^&*()_+|~=`{}\[\]:";'<>?,.\/]/;const capital=/[A-Z]/;if(passwordOptions.letters&&!letters.test(fieldValue)){errorContainer.classList.add("null-form-error");return customErrorMessages.letters||"Password must contain at least one letter.";}
if(passwordOptions.numbers&&!numbers.test(fieldValue)){errorContainer.classList.add("null-form-error");return customErrorMessages.numbers||"Password must contain at least one number.";}
if(passwordOptions.symbols&&!symbols.test(fieldValue)){errorContainer.classList.add("null-form-error");return customErrorMessages.symbols||"Password must contain at least one symbol.";}
if(passwordOptions.capital&&!capital.test(fieldValue)){errorContainer.classList.add("null-form-error");return customErrorMessages.capital||"Password must contain at least one capital letter.";}
return"";}
function null_process_field_value(fieldValue,fieldParams){if(fieldParams.removeSpaces){fieldValue=fieldValue.toLowerCase().replace(/\s+/g,' ').trim();}
if(fieldParams.capitalizeFirstWord){fieldValue=fieldValue.toLowerCase().charAt(0).toUpperCase()+fieldValue.slice(1);}
if(fieldParams.capitalizeEachWord){fieldValue=fieldValue.toLowerCase().replace(/\b\w/g,(char)=>char.toUpperCase());}
return fieldValue;}
function null_form_validate(selector,args,errorMessages){if(typeof errorMessages==="undefined"){errorMessages={};}
let button=document.querySelector(selector);if(button==null){return}
let form=button.parentElement;null_initialize_form_fields(form,args);button.addEventListener("click",function(e){e.preventDefault();let hasError=false;let processedData={};for(let field in args){let input=form.querySelector("#"+field);let errorContainer=form.querySelector(`[data-null-for="${field}"]`);if(!errorContainer){console.error(`Error container not found for field:${field}`);continue;}
errorContainer.innerHTML="";errorContainer.classList.remove("null-form-error");errorContainer.classList.remove("null-form-success");let fieldValue=input.value.trim();let fieldParams=args[field];fieldValue=null_process_field_value(fieldValue,fieldParams);processedData[field]=fieldValue;if(args[field].debugMode){console.log(`Input ID:${field},Value:${fieldValue}`);}
if(fieldParams.required&&fieldValue===""){hasError=true;errorContainer.innerHTML=errorMessages.required||`Field is required`;errorContainer.classList.add("null-form-error");}
else if(fieldParams.type){if(fieldParams.min&&fieldValue.length<fieldParams.min){hasError=true;errorContainer.innerHTML=errorMessages.min||`Minimum length is ${fieldParams.min}characters.`;errorContainer.classList.add("null-form-error");}
else if(fieldParams.max&&fieldValue.length>fieldParams.max){hasError=true;errorContainer.innerHTML=errorMessages.max||`Maximum length is ${fieldParams.max}characters.`;errorContainer.classList.add("null-form-error");}
else{if(fieldParams.type==="text"&&!/^[a-zA-Z\s]*$/.test(fieldValue)){hasError=true;errorContainer.innerHTML=errorMessages.text||"Invalid input. Only letters and spaces allowed.";errorContainer.classList.add("null-form-error");}else if(fieldParams.type==="text"&&fieldParams.showSuccess){errorContainer.innerHTML=fieldValue;errorContainer.classList.add("null-form-success");}else if(fieldParams.type==="password"){const passwordError=null_password_validation(fieldValue,fieldParams.passwordOptions,fieldParams.customPasswordErrorMessages,errorContainer);if(passwordError){hasError=true;errorContainer.innerHTML=passwordError;}}else if(fieldParams.type==="number"&&!/^\d+$/.test(fieldValue)){hasError=true;errorContainer.innerHTML=errorMessages.number||`Invalid input.Only numbers allowed`;errorContainer.classList.add("null-form-error");}else if(fieldParams.type==="number"&&fieldParams.showSuccess){errorContainer.innerHTML=fieldValue;errorContainer.classList.add("null-form-success");}else if(fieldParams.type==="email"&&!/^[\w-]+(\.[\w-]+)*@([\w-]+\.)+[a-zA-Z]{2,7}$/.test(fieldValue)){hasError=true;errorContainer.innerHTML=errorMessages.email||`Invalid email address`;errorContainer.classList.add("null-form-error");}else if(fieldParams.type==="email"&&fieldParams.showSuccess){errorContainer.innerHTML=fieldValue;errorContainer.classList.add("null-form-success");}}}
if(!hasError&&fieldParams.showSuccess){errorContainer.innerHTML=fieldValue;errorContainer.classList.add("null-form-success");}}
if(!hasError){form.submit();}});}